server:
  port: 9090

spring:
  application:
    name: ms-Minio
  servlet:
    multipart:
      max-file-size: 20MB

minio:
  url: http://127.0.0.1:9000
  access:
    secret: minioadmin
    key: minioadmin
  bucket:
    name: certidigital

